### ISSUE TITLE
Jupyter and Task 1.2

### ISSUE THREAD

**Issue by geneticginger** [sksuzuki/How-to-Learn-to-Code-2018#17]
Are you guys able to go over more how to interface with Jupyter and to know when we need to pull Jupyter code to test on our computer? For example, the task 1.2 I don't know how to do in Jupyter because it's using files so troubleshooting of this task is a little more difficult.

**Comment by geneticginger** [comment]
I'm also getting an error with the following code that 'header' and 'file' aren't defined and I don't know why since they are defined. 
![screen shot 2018-05-30 at 6 21 54 pm](https://user-images.githubusercontent.com/39745724/40750770-5cc8ae3e-6436-11e8-8a43-e68b2e2eca83.JPG)

**Comment by Jessime** [comment]
Yea, of course! I'll do a slower, more in depth demonstration of jupyter tomorrow by using it to build a solution for level 0. 

---

As you have it now, `header` isn't going to be defined in your `print` function. You have defined a variable called `header` inside of your function `headers`, but it's only defined within the "scope" of that function. If you tab `print(header)` over to be in the same scope as the rest of the function, you won't have that error.  But, you'll also need your function to return the headers, so don't forget to add that as well.

We can talk more about scope tomorrow if necessary.

**Comment by laurafisch9** [comment]
I am confused why 
header = " " 
has to be defined. Why is it a space and what is the purpose of this line of code?

**Comment by geneticginger** [comment]
I was trying to make an empty list to append the line that started with '>' to
