### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by Jessime** [sksuzuki/How-to-Learn-to-Code-2018#20]
Level 0 solutions are up.

**Comment by Jessime** [comment]
Level 1 solutions are also up [here](https://github.com/sksuzuki/How-to-Learn-to-Code-2018/tree/master/solutions).

**Comment by Jessime** [comment]
Just a reminder that we're having "office hours" today!

> Event Confirmed:
> Start:     6/11/2018 @ 4:00PM
> Finish:  6/11/2018 @ 5:30PM
> Venue: 6004 Marsico
> Meeting_Title: How to Learn to Code

**Comment by Jessime** [comment]
https://abstrusegoose.com/249

**Comment by Jessime** [comment]
Hey all,

I know a lot of you are busy with quals and other things, but hopefully everyone can make it to class today. Today's my last day and I'd love to say goodbye to everyone! See you in a bit.

**Comment by KimikoMcGirr** [comment]
[Level 2 solutions](https://github.com/sksuzuki/How-to-Learn-to-Code-2018/tree/master/solutions) are up.

**Comment by KimikoMcGirr** [comment]
The [solutions to level 3 tasks](https://github.com/sksuzuki/How-to-Learn-to-Code-2018/tree/master/solutions) are now up! We'll go over level 3 in class on Thursday. Please reach out to me or post in the issues if you're stuck on anything. See you all then!
