### ISSUE TITLE
Problem in thinking about mutation rate?

### ISSUE THREAD

**Issue by arober51** [sksuzuki/How-to-Learn-to-Code-2018#22]
Hello!
I've (hopefully) attached the code I've written for problem 1. 
The code seems to work if I run it with the reference.fa, control.fa, theraptrix.fa files respectively, and I get a p value that is written to a file. However, when I upload this code on the class website, I get an error saying my answer is incorrect. I was wondering if this is due to a flaw in the way I'm thinking about the problem, or if it's due to syntax, etc. 

I'm not super familiar with the zip function, or list comprehension, so maybe my roundabout way of solving the problem is the problem.

Thanks for the help, and sorry for the last minute question!!

[problem1.txt](https://github.com/sksuzuki/How-to-Learn-to-Code-2018/files/2073012/problem1.txt)

**Comment by Jessime** [comment]
Hey! Your p-value is super close, but not quite correct. I'm looking over your code now, but haven't spotted the bug yet. I'll keep you posted.

**Comment by Jessime** [comment]
Turns out to be an easy fix! On lines 21, 25, and 29, you're trimming the first nucleotide off of the sequences  by doing `[1:]`. 

Based on your variable names, I suspect this is a leftover from processing headers instead of the sequences.

**Comment by arober51** [comment]
Whoops! Definitely an easy enough fix. Thanks so much for looking over it and catching that for me!!
